### PR TITLE
ENH add uniform/optimized rolling and tests for it

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds new uniform/optimized rolling functionality to the scheduler. It allows for special times during rolling surveys where the survey will come back to uniform. 

See PRs https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/4 and https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/3 for detailed tests.

This PR has the scheme in https://github.com/lsst-sims/sims_featureScheduler_runs3.4/pull/4.

### CODE REVIEW

**Comment by beckermr** [comment]
@yoachim @rhiannonlynne This PR is ready for review. I ran the test that I added locally and it passes. You'll need to approve the workflow runs for the tests in CI to go.

We'll probably want to do one more test sim after this PR to make sure it all works end to end. I am happy to confirm that if you all can run it using the code here.

**Comment by beckermr** [comment]
Oh this is going to be painful. It makes you kick off the CI each time. 🤦‍♂️

**Comment by rhiannonlynne** [comment]
Oh that's odd .. I thought that the configuration was such that once you were approved, it would let you rerun the actions. Perhaps things have changed at the lsst org level or maybe it's just different on rubin-scheduler compared to rubin-sim. I'll see if I notice anything obvious.

**Comment by beckermr** [comment]
happy monday @rhiannonlynne @yoachim! Can we approve this job again to see if it passes?

**Comment by beckermr** [comment]
Woo hooo! Tests pass and everything looks good on linting. @rhiannonlynne @yoachim This is definitely ready for review! Please let me know what I can do to get it merged. Thank you!

**Comment by beckermr** [comment]
bumping @rhiannonlynne and @yoachim to see if we can get this merged!

**Comment by beckermr** [comment]
huzaah!

**Pull request merged**
